tap "azure/functions"
tap "commitdev/zero"
tap "getsentry/tools"
tap "github/gh"
tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/mssql-release"
tap "tilt-dev/tap"
tap "wpengine/wpe-cli"
brew "readline"
brew "xz"
brew "awscli"
brew "python@3.8"
brew "azure-cli"
brew "bash"
brew "glib"
brew "certbot"
brew "circleci"
brew "composer"
brew "coreutils"
brew "diff-so-fancy"
brew "dnsmasq", restart_service: true
brew "doctl"
brew "duti"
brew "erlang"
brew "elixir"
brew "exiftool"
brew "libevent"
brew "harfbuzz"
brew "ffmpeg"
brew "fish"
brew "flow-cli"
brew "freetds"
brew "isl"
brew "libmpc"
brew "krb5"
brew "libdap"
brew "nss"
brew "poppler"
brew "gdal"
brew "geoip"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "grc"
brew "hasura-cli"
brew "helm"
brew "htop"
brew "jq"
brew "kind"
brew "kompose"
brew "kustomize"
brew "libmagic"
brew "mas"
brew "mitmproxy"
brew "mkcert"
brew "mono"
brew "protobuf"
brew "mysql"
brew "node"
brew "node-build"
brew "nodenv"
brew "openjdk"
brew "perl-build"
brew "php"
brew "php-cs-fixer"
brew "pinentry-mac"
brew "plenv"
brew "postgresql"
brew "protobuf-c"
brew "sfcgal"
brew "postgis"
brew "prototool"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "rsync"
brew "ruby"
brew "terminal-notifier"
brew "terraform"
brew "thefuck"
brew "tmux"
brew "trash-cli"
brew "watchman"
brew "wget"
brew "wireguard-tools"
brew "wp-cli"
brew "yarn"
brew "azure/functions/azure-functions-core-tools@3"
brew "commitdev/zero/zero"
brew "getsentry/tools/sentry-cli"
brew "microsoft/mssql-release/msodbcsql"
brew "microsoft/mssql-release/msodbcsql17"
brew "microsoft/mssql-release/mssql-tools"
brew "tilt-dev/tap/ctlptl"
brew "tilt-dev/tap/tilt"
cask "1password"
cask "adoptopenjdk"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "authy"
cask "clockify"
cask "cyberduck"
cask "dashlane"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "eclipse-jee"
cask "fantastical"
cask "firefox"
cask "font-fira-code"
cask "font-powerline-symbols"
cask "fork"
cask "gitahead"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "harvest"
cask "intellij-idea-ce"
cask "iterm2"
cask "java"
cask "lens"
cask "mailplane"
cask "meld"
cask "messenger"
cask "miro-formerly-realtimeboard"
cask "ngrok"
cask "notion"
cask "poedit"
cask "postman"
cask "powershell"
cask "sequel-pro"
cask "signal"
cask "sketch"
cask "sketch-toolbox"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "telegram"
cask "the-unarchiver"
cask "toggl"
cask "transmission"
cask "transmit"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Boom 2", id: 948176063
mas "GarageBand", id: 682658836
mas "Harvest", id: 506189836
mas "iMovie", id: 408981434
mas "Jira", id: 1475897096
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Mimeo Photos", id: 1282504627
mas "monday.com", id: 1298450641
mas "Quip", id: 1003160018
mas "Sleep Control Center", id: 946798523
mas "Trello", id: 1278508951
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
