tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "wpengine/wpe-cli"
brew "diff-so-fancy"
brew "fish"
brew "git"
brew "openssl"
brew "readline"
brew "sqlite"
brew "xz"
brew "grc"
brew "mas"
brew "nodenv"
brew "perl-build"
brew "plenv"
brew "pyenv"
brew "rbenv"
brew "rsync"
brew "terminal-notifier"
brew "thefuck"
brew "tmux"
brew "trash-cli"
brew "wpengine/wpe-cli/wpe-cli"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "authy"
cask "caffeine"
cask "dashlane"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "font-fira-code"
cask "font-powerline-symbols"
cask "google-chrome"
cask "intellij-idea-ce"
cask "iterm2"
cask "mailplane"
cask "messenger"
cask "sketch"
cask "sketch-toolbox"
cask "skype"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "toggl"
cask "transmission"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoomus"
mas "Boom 2", id: 948176063
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Quip", id: 1003160018
mas "Trello", id: 1278508951
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
