command_timeout=2000

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$kubernetes\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

[gcloud]
format = 'on [$symbol$active(\($project\))]($style) '
style = "bold yellow"
symbol = "☁️  "
[gcloud.region_aliases]
australia-southeast1 = "au1"
australia-southeast2 = "au2"
[gcloud.project_aliases]
foratherapy-dev = "dev"
foratherapy-staging = "staging"
foratherapy-prod = "prod"

[kubernetes]
format = 'on [$symbol$context(\($namespace\))](dimmed green) '
symbol = "⛵ "
disabled = false
[kubernetes.context_aliases]
".*rancher-desktop.*" = "rancher"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[hostname]
ssh_symbol = "🌐"

